Repository davep/peplum, pull requests merged in 2025-01, with the labels that each got.

#6 Work around likely Textual bug with `OptionList`
  src/peplum/app/screens/main.py
Labels: Cosmetic, Housekeeping

#7 Add the date created to the list of things free-text-searched
  ChangeLog.md
  src/peplum/peps/pep.py
Labels: Enhancement

#8 Update the ChangeLog with #6
  ChangeLog.md
Labels: Documentation, Housekeeping

#9 Code tidy
  src/peplum/app/commands/base.py
Labels: Housekeeping

#10 Documentation tidying
  src/peplum/app/data/peps.py
  src/peplum/app/widgets/pep_details.py
Labels: Documentation, Housekeeping

#11 More date parser testing
  tests/unit/test_pep_dates.py
Labels: Housekeeping

#12 Sort version commands by actual version sort order
  ChangeLog.md
  src/peplum/app/providers/python_versions.py
Labels: Enhancement, Cosmetic

#13 Add support for local annotations
  ChangeLog.md
  README.md
  src/peplum/app/commands/__init__.py
  src/peplum/app/commands/main.py
  src/peplum/app/data/__init__.py
  src/peplum/app/data/notes.py
  src/peplum/app/data/pep.py
  src/peplum/app/data/peps.py
  src/peplum/app/messages/main.py
  src/peplum/app/providers/main.py
  src/peplum/app/screens/main.py
  src/peplum/app/screens/notes_editor.py
  src/peplum/app/widgets/pep_details.py
  src/peplum/app/widgets/peps_view.py
  src/peplum/peps/__init__.py
  src/peplum/peps/api.py
  tests/unit/test_notes.py
  tests/unit/test_pep_annotation.py
  tests/unit/test_pep_dates.py
  tests/unit/test_peps.py
Labels: Enhancement, TODO

#14 Allow some more common list-navigation keys in option lists
  src/peplum/app/widgets/extended_option_list.py
Labels: Enhancement

#16 Rename a non-action so that it's not called an action
  src/peplum/app/screens/main.py
Labels: Housekeeping

#17 Add support for locally viewing the source of a PEP
  ChangeLog.md
  README.md
  src/peplum/app/commands/__init__.py
  src/peplum/app/commands/main.py
  src/peplum/app/data/__init__.py
  src/peplum/app/data/locations.py
  src/peplum/app/peplum.py
  src/peplum/app/providers/main.py
  src/peplum/app/screens/main.py
  src/peplum/app/screens/pep_viewer.py
  src/peplum/app/widgets/__init__.py
  src/peplum/app/widgets/text_viewer.py
  src/peplum/peps/api.py
Labels: Enhancement, TODO

#18 Tweak the cosmetics of the notes editor
  ChangeLog.md
  src/peplum/app/screens/notes_editor.py
Labels: Enhancement, Cosmetic

#19 Drop Python 3.8
  .github/workflows/style-lint-and-test.yaml
  ChangeLog.md
  pyproject.toml
Labels: Housekeeping

#20 Add support for saving a PEP's source to a file
  ChangeLog.md
  pyproject.toml
  requirements-dev.lock
  requirements.lock
  src/peplum/app/screens/confirm.py
  src/peplum/app/screens/pep_viewer.py
Labels: Enhancement, TODO

#22 Simplify the compose of the main screen
  src/peplum/app/screens/main.py
Labels: Housekeeping

#23 Tidy the typing around the search input dialog
  src/peplum/app/screens/search_input.py
Labels: Housekeeping

#24 Default the filename when saving a PEP's source
  ChangeLog.md
  pyproject.toml
  requirements-dev.lock
  requirements.lock
  src/peplum/app/screens/pep_viewer.py
Labels: Enhancement

#25 Add a target for running up via textual serve
  Makefile
Labels: Housekeeping

#26 Remove OptionList scrollbar CSS from the app
  src/peplum/app/peplum.py
Labels: Housekeeping

#27 Swap the default for `SHOW_IN_FOOTER`
  src/peplum/app/commands/base.py
  src/peplum/app/commands/filtering.py
  src/peplum/app/commands/finding.py
  src/peplum/app/commands/main.py
  src/peplum/app/commands/navigation_sorting.py
  src/peplum/app/commands/peps_sorting.py
Labels: Housekeeping
